### ISSUE TITLE
Cannot communicate with Dev-BE

### ISSUE THREAD

**Issue by sherlockwisdom** [smswithoutborders/SMSWithoutBorders-OpenAPI#4]
I cannot find instructions on where to put the instructions to set up communication from openAPI to Dev-BE

**Comment by PromiseFru** [comment]
Hello @sherlockwisdom this has been added here 
https://github.com/smswithoutborders/SMSWithoutBorders-Dev-BE/blob/staging/docs/CONFIGURATIONS.md#products-configurations

**Comment by sherlockwisdom** [comment]
Thank you!
